apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "key-generator.fullname" . }}
  labels:
    app: {{ include "key-generator.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "key-generator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "key-generator.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "main.py"