apiVersion: v1
kind: Service
metadata:
  name: {{ include "key-generator.fullname" . }}
  labels:
    app: {{ include "key-generator.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.port }}
  selector:
    app: {{ include "key-generator.name" . }}
  type: {{ .Values.service.type }}